### ISSUE TITLE
Backend hanging - `compatibilitytools.d` directory not created by default

### ISSUE THREAD

**Issue by dolphin-evorobey** [FlashyReese/decky-wine-cellar#6]
maybe any logs somewhere?

**Comment by FlashyReese** [comment]
Can you provide the following log files if any
`journalctl --since today --until "tomorrow" -u plugin_loader.service > ~/plugin_loader.log` - This will output to your home folder with a file called `plugin_loader.log`
`~/homebrew/logs/decky-wine-cellar/*.log` - There should be a `wine-cask.log` and a `<DATETIME>.log`

Are you running official SteamDeckOS?

Did you recently update the plugin or was this on a first time installation? (If it was an update you might need to uninstall then reinstall)

**Comment by pretzelise** [comment]
Hi! Please see the excerpt from the journal below:
`Sep 07 17:04:10 steamdeck PluginLoader[3869]: [Wine Cask] 2023-09-07 17:04:10 INFO Logging to: /home/deck/homebrew/logs/decky-wine-cellar/wine-cask.log
Sep 07 17:04:10 steamdeck PluginLoader[3869]: [Wine Cask] 2023-09-07 17:04:10 INFO Using DECKY_USER_HOME: /home/deck
Sep 07 17:04:10 steamdeck PluginLoader[3869]: [Wine Cask] 2023-09-07 17:04:10 INFO Looking for Steam directory in /home/deck
Sep 07 17:04:10 steamdeck PluginLoader[3869]: [Wine Cask] 2023-09-07 17:04:10 INFO Found Steam directory: /home/deck/.local/share/Steam
Sep 07 17:04:10 steamdeck PluginLoader[3869]: thread 'main' panicked at 'Failed to get list of compatibility tools: CompatibilityToolsDirectoryNotFound', src/wine_cask/app.rs:197:14
Sep 07 17:04:10 steamdeck PluginLoader[3869]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

I was able to resolve this and get it working by creating the `/home/deck/.local/share/Steam/compatibilitytools.d/` directory, uninstalling Wine Cellar, then installing again.

From a quick review of the code, I think the plugin is meant to create this directory if it doesn't exist but it doesn't seem to have worked.

Hope this helps!

**Comment by FlashyReese** [comment]
> From a quick review of the code, I think the plugin is meant to create this directory if it doesn't exist but it doesn't seem to have worked.

I discovered this a few days ago, that's why it's not in the `0.1.2` release.

I will be leaving this open for tracking purposes until I push an update to the store.
